name: nlp_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - nltk
  - scipy
  - gensim
  - numpy
  - pip:
      # aquí puedes añadir librerías extra de pip si lo necesitas
      # - spacy
      # - stanza
